# Generated by Django 5.2.4 on 2025-10-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_company_name_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], default='onsite', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification_level',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='mid', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
