# Generated by Django 5.2.4 on 2025-10-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_benefits_job_job_overview_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/company/'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_in_company',
            field=models.CharField(blank=True, choices=[('hr_manager', 'HR Manager'), ('talent_acquisition_specialist', 'Talent Acquisition Specialist'), ('recruiter', 'Recruiter'), ('hiring_manager', 'Hiring Manager'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='media/verification/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='media/resumes/'),
        ),
    ]
